[pytest]
minversion = 9.0
testpaths = tests
pythonpath = .
asyncio_mode = strict
addopts = -ra --strict-markers --strict-config
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning
