import { useCallback, useEffect, useState } from "react";
import { fetchIncidentsHistory } from "@/lib/api-contract";
import type { PersistedInvestigation } from "@/types/api";
import { PageHeader } from "@/components/ui/PageHeader";
import { LoadingSkeleton } from "@/components/noc/LoadingSkeleton";
import { Button } from "@/components/ui/Button";

function draftFromSession(item: PersistedInvestigation): string {
  const lines = [
    `# Post-Mortem Draft — ${item.service || "Incident"} (${item.severity || "—"})`,
    "",
    `**Session:** ${item.session_id}`,
    `**Service:** ${item.service || "—"} · **Environment:** ${item.environment || "—"}`,
    `**Severity:** ${item.severity || "—"}`,
    "",
    "## Summary",
    item.symptom || "No summary captured.",
    "",
    "## Timeline",
    `- Alert / investigation opened`,
    `- PITER triage completed`,
    "",
    "## Root cause (draft)",
    "To be confirmed after investigation.",
    "",
    "## Action items",
    "- [ ] Validate deployment correlation",
    "- [ ] Update runbook if gap found",
    "- [ ] Confirm escalation path with service owner",
    "",
    "_Generated by PITER Ops — edit before publishing._",
  ];
  return lines.join("\n");
}

export function PostMortemsPage() {
  const [items, setItems] = useState<PersistedInvestigation[]>([]);
  const [loading, setLoading] = useState(true);
  const [draft, setDraft] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const data = await fetchIncidentsHistory(30);
      setItems(data.investigations || []);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <div className="grid-stack">
      <PageHeader
        title="Post-Mortems"
        subtitle="Draft incident reviews from session memory — not auto-published"
      />

      {loading ? <LoadingSkeleton lines={5} /> : null}

      {!loading && items.length === 0 ? (
        <p className="mono" style={{ color: "var(--text-muted)" }}>
          No closed investigations yet. Run a P1 analysis to seed post-mortem drafts.
        </p>
      ) : null}

      <ul className="postmortem-list">
        {items.map((item) => (
          <li key={item.session_id} className="panel postmortem-row">
            <div>
              <strong>{item.service || "Investigation"}</strong>
              <span className="mono" style={{ marginLeft: 8, color: "var(--text-muted)" }}>
                {item.severity || "—"}
              </span>
              <p style={{ margin: "6px 0 0", fontSize: "0.8125rem" }}>
                {item.symptom?.slice(0, 120) || "No summary"}
              </p>
            </div>
            <Button variant="secondary" size="sm" onClick={() => setDraft(draftFromSession(item))}>
              Create Post-Mortem Draft
            </Button>
          </li>
        ))}
      </ul>

      {draft ? (
        <section className="panel postmortem-draft">
          <h2 className="panel-title">Draft preview</h2>
          <pre className="postmortem-draft-body">{draft}</pre>
          <Button variant="ghost" size="sm" onClick={() => setDraft(null)}>
            Close draft
          </Button>
        </section>
      ) : null}
    </div>
  );
}
